config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


#VERB    URL           TO: CONTROLLER_NAME#ACTION_NAME


  resources :restaurants

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  validates :name, presence: true

  def pretty_name
    puts "#{name} is pretty"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  # before_action :set_restaurant, except: [:index, :new, :create]


  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # handles the creation of the restaurant

    Restaurant.create!(restaurant_params)

    redirect_to "/restaurants"
    # redirects to either index or show
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<H1>Change something on your restaurant:</H1>

<%= render "form", restaurant: @restaurant  %>

<!-- @restaurant is the one which id is the same as the one in the url -->

app/views/restaurants/index.html.erb
<h1>Those are all my restaurants:</h1>

<ul>

  <% @restaurants.each do |restaurant| %>
    <!-- restaurant => is a restaurant instance -->
    <!-- /restaurants/8 -->
    <li> <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
      <%= link_to "Edit", edit_restaurant_path(restaurant) %> -
      <%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
    </li>
  <% end %>

</ul>

<%= link_to "Create new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant:</h1>

<%= render "form", restaurant: @restaurant %>

<%= link_to "Back",  restaurants_path %>

app/views/restaurants/show.html.erb
<h2>This is <%= @restaurant.name %></h2>
<h3>Our rating is <%= @restaurant.rating %> </h3>
<h3>We're located at: <%= @restaurant.address %></h3>

<%= link_to "Back", restaurants_path %>